  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization

  resources:
  - ../../../base

# namespace: production-database # VEM DO APP ARGOCD

# patchesStrategicMerge:
#   - patch-replicas.yaml
