apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- statefulset.yaml

commonLabels:
  app: clickhouse
  component: database
  managed-by: kustomize
  part-of: platform