apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- service-client.yaml
- configmap.yaml
- pvc.yaml
- secret.yaml

commonLabels:
  app: redpanda
  component: messaging
  managed-by: kustomize
  part-of: platform
