apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  config.toml: |
    [checks]

    [checks.clickhouse]
    type = "clickhouse"
    host = "clickhouse"
    port = 8123
    db = "default"
    user = "default"
    password = "password"

    [checks.application1]
    type = "service"
    endpoint = "http://example-service:8080/health"
    method = "GET"
    timeout = 5

    [checks.novo_check]
    type = "tipo"
    param1 = "valor1"
    param2 = "valor2"