apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  config.toml: |
    [general]
    log_level = "info"
    port = 8080

    [clickhouse]
    host = "clickhouse"
    port = 8123
    database = "default"

    [checks]
    example_project = [
      { name = "check_1", type = "ping", target = "localhost" }
    ]
