apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  TELESCOPE_PORT: "8080"
  TELESCOPE_CLICKHOUSE_HOST: "clickhouse-service"  # servi√ßo do clickhouse
  TELESCOPE_CLICKHOUSE_PORT: "9000"
  TELESCOPE_CLICKHOUSE_DB: "logs"
