apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  config.toml: |
    [server]
    port = 8089

    [clickhouse]
    host = "clickhouse"
    port = 8123
    database = "default"

    [mysql]
    dsn = "root:root123@tcp(mysql.production-database.svc.cluster.local:3306)/clickvisual?charset=utf8mb4&parseTime=True&loc=Local&tls=false&allowNativePasswords=true"

    [auth]
    type = "disabled"