apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
  namespace: observability-production
data:
  config.toml: |
    [server]
    port = 8000

    [clickhouse]
    host = "clickhouse"
    port = 8123
    database = "default"

    [mysql]
    host = "mysql"
    port = 3306
    database = "clickvisual"
