apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  config.toml: |
    [checks]

    [checks.clickhouse]
    type = "clickhouse"
    host = "clickhouse"
    port = 8123
    db = "default"

    [checks.application1]
    type = "service"
    endpoint = "http://example-service:8080/health"
