apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = 8080

    [checks]

    [checks.httpbin]
      [[checks.httpbin.entries]]
      name = "httpbin-status"
      url = "https://httpbin.org/status/200"
      interval = 60
      timeout = 5
