apiVersion: apps/v1
kind: Deployment
metadata:
  name: telescope
  namespace: observability-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telescope
  template:
    metadata:
      labels:
        app: telescope
    spec:
      containers:
        - name: telescope
          image: ghcr.io/clickvisual/telescope:v1.5.4
          imagePullPolicy: IfNotPresent

          workingDir: /app

          volumeMounts:
            - name: config
              mountPath: /app/config.toml
              subPath: config.toml

      volumes:
        - name: config
          configMap:
            name: telescope-config
