apiVersion: apps/v1
kind: Deployment
metadata:
  name: telescope
  labels:
    app: telescope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telescope
  template:
    metadata:
      labels:
        app: telescope
    spec:
      containers:
      - name: telescope
        image: mozilla/telescope:v6.20.0
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: telescope-secret
        volumeMounts:
        - name: telescope-config
          mountPath: /config.toml
          subPath: config.toml
        - name: telescope-data
          mountPath: /data
      volumes:
      - name: telescope-config
        configMap:
          name: telescope-config
      - name: telescope-data
        persistentVolumeClaim:
          claimName: telescope-pvc
