apiVersion: apps/v1
kind: Deployment
metadata:
  name: telescope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telescope
  template:
    metadata:
      labels:
        app: telescope
    spec:
      containers:
        - name: telescope
          image: mozilla/telescope:v6.20.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: telescope-secret
          volumeMounts:
            - name: config-volume
              mountPath: /config.toml
              subPath: config.toml
      volumes:
        - name: config-volume
          configMap:
            name: telescope-config
