apiVersion: apps/v1
kind: Deployment
metadata:
  name: telescope
  labels:
    app: telescope
spec:
  replicas: 1

  selector:
    matchLabels:
      app: telescope   # üîí IMUT√ÅVEL

  template:
    metadata:
      labels:
        app: telescope # üîí IGUAL AO SELECTOR
    spec:
      containers:
        - name: telescope
          image: mozilla/telescope:v6.20.0

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: telescope-config
              mountPath: /config.toml
              subPath: config.toml

            - name: telescope-data
              mountPath: /data

      volumes:
        - name: telescope-config
          configMap:
            name: telescope-config

        - name: telescope-data
          persistentVolumeClaim:
            claimName: telescope-pvc
