apiVersion: apps/v1
kind: Deployment
metadata:
  name: telescope
  namespace: observability-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telescope
  template:
    metadata:
      labels:
        app: telescope
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: telescope
          image: clickvisual/clickvisual:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: EGO_CONFIG_PATH
              value: /app/config.toml

          volumeMounts:
            - name: config
              mountPath: /app/config.toml
              subPath: config.toml

      volumes:
        - name: config
          configMap:
            name: telescope-config
