apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ghcr-secret.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: telescope
  app.kubernetes.io/component: observability
  managed-by: kustomize
