all:
  hosts:
    localhost:
      ansible_connection: local     # roda no WSL localmente
      ansible_become: yes          # permite usar sudo
      ansible_become_method: sudo
      ansible_become_user: root    # ou seu usuário se já for sudo
      ansible_python_interpreter: /usr/bin/python3  # garante Python correto
