apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: production-namespace
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000        # porta interna do cluster
      targetPort: 3000  # porta do container
      nodePort: 32000   # porta externa para navegador
