- name: Verificar se k9s j치 est치 instalado
  command: k9s version
  register: k9s_check
  ignore_errors: true
  changed_when: false

- name: Definir arquitetura
  set_fact:
    k9s_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

- name: Baixar k9s
  get_url:
    url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ k9s_arch }}.tar.gz"
    dest: /tmp/k9s.tar.gz
    mode: '0644'
  when: k9s_check.rc != 0

- name: Extrair k9s
  unarchive:
    src: /tmp/k9s.tar.gz
    dest: /tmp
    remote_src: yes
  when: k9s_check.rc != 0

- name: Instalar bin치rio do k9s
  become: true
  copy:
    src: /tmp/k9s
    dest: /usr/local/bin/k9s
    mode: '0755'
    remote_src: yes
  when: k9s_check.rc != 0

- name: Remover arquivos tempor치rios
  file:
    path: /tmp/k9s.tar.gz
    state: absent
  when: k9s_check.rc != 0
