apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/messaging

namespace: production-messaging # VEM DO APP ARGOCD

# patchesStrategicMerge:
#   - patch-replicas.yaml
