apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Este diretório contém apenas definições de jobs para o Prometheus
# Não é aplicável diretamente, é referenciado pelo configMapGenerator