# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

namespace: main-namespace
nameSuffix: -staging
resources:
  - ../../base
patches:
  - path: main-patch.yaml
commonLabels:
  env: staging