# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

namespace: main-namespace-staging
# nameSuffix: -staging
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: main-patch.yaml
commonLabels:
  env: staging