apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  database: clickvisual

# data:
#   my.cnf: |
#     [mysqld]
#     character-set-server=utf8mb4
#     collation-server=utf8mb4_unicode_ci
#     default-authentication-plugin=mysql_native_password
#     max_connections=100
#     innodb_buffer_pool_size=1G
#     innodb_log_file_size=256M
#     skip-name-resolve
#     sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    
#     [client]
#     default-character-set=utf8mb4