apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml


commonLabels:
  app: mysql
  component: database
  managed-by: kustomize
  part-of: platform

# secretGenerator:
# - name: mysql-secret
#   literals:
#   - root-password=senha-segreda
#   - username=appuser
#   - password=apppassword
#   - database=appdb