apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main-namespace-production
resources:
  - ../../../base/observability
  - ../namespace.yaml   # cria namespace do overlay
commonLabels:
  env: production