apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/observability

namespace: production-observability # VEM DO APP ARGOCD

# patchesStrategicMerge:
#   - patch-replicas.yaml
