apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database
- messaging
- observability

# namespace: production-database # VEM DO APP ARGOCD

# patchesStrategicMerge:
#   - patch-replicas.yaml
