apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: teste.com.br
      http:
        paths:
          - path: /main
            pathType: Prefix
            backend:
              service:
                name: external-main-app
                port:
                  number: 80
