
namespace: main-namespace-production
# nameSuffix: -production
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
  - external-service.yaml
  - external-endpoints.yaml
patches:
  - path: main-patch.yaml
commonLabels:
  env: production