namespace: main-namespace-production
resources:
- ../../base
- namespace.yaml
  # - ingress.yaml

patches:
- path: main-patch.yaml
commonLabels:
  env: production
  
images:
- name: ghcr.io/fabiossena/anchor-api
  newName: ghcr.io/fabiossena/anchor-api
  newTag: v1.0.1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
