apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: observability

resources:
  # - namespace.yaml # it comes from the app ArgoCD

  # - node-exporter
  # - prometheus
  # - grafana

  - clickvisual
  - telescope

commonLabels:
  app.kubernetes.io/part-of: observability
