apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability 

resources:
  - clickvisual
  - telescope
  # - grafana
  # - prometheus
  # - node-exporter

commonLabels:
  app.kubernetes.io/part-of: observability
  managed-by: kustomize
