apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml

commonLabels:
  app: kibana
  component: search
  managed-by: kustomize
  part-of: platform

secretGenerator:
- name: kibana-secret
  literals:
  - encryption-key=something_at_least_32_characters
  - reporting-encryption-key=something_at_least_32_characters