apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress-qa
  labels:
    app: anchor-api
namespace: main-namespace-qa
spec:
  rules:
  - host: app.fsysolutions.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anchor-api
            port:
              number: 80