namespace: main-namespace-qa
# nameSuffix: -qa
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
  
patches:
  - path: main-patch.yaml
commonLabels:
  env: qa

images:
- name: ghcr.io/fabiossena/anchor-api
  newName: ghcr.io/fabiossena/anchor-api
  newTag: v1