apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main-namespace-qa

resources:
- namespace.yaml
- ../../base
- ingress.yaml
  
patches:
- path: main-patch.yaml
commonLabels:
  env: qa

images:
- name: ghcr.io/fabiossena/anchor-api
  newName: ghcr.io/fabiossena/anchor-api
  newTag: f6ba58dd560a12a45409f81ee126df15a69b19e5
