apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - Chart.yaml
  # - values.yaml
  - templates/deployment.yaml
  - templates/service.yaml
  - templates/pvc.yaml
  - templates/configmap.yaml
  - templates/configmap-db.yaml