apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis
  - postgres
  # - mysql
  # - clickhouse

commonLabels:
  app.kubernetes.io/part-of: database
  managed-by: kustomize
