apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: app-qa.fsysolutions.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fss-site
            port:
              number: 80
