apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qa-ingress
  namespace: qa-namespace
  labels:
    app: anchor-api
spec:
  ingressClassName: traefik
  rules:
  - host: app.fsysolutions.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anchor-api
            port:
              number: 80
