apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-namespace

resources:
- namespace.yaml
- ../../base
- ingress.yaml
  
patches:
- path: main-patch.yaml
commonLabels:
  env: qa

images:
- name: ghcr.io/fabiossena/anchor-api
  newName: ghcr.io/fabiossena/anchor-api
  newTag: 9bf39b2825d6f989dd3ff26ea15e59873d018b3a

- name: ghcr.io/fabiossena/redpanda-producer-api
  newName: ghcr.io/fabiossena/redpanda-producer-api
  newTag: v1.0.0
