apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana
    component: search
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: ["http://elasticsearch-client:9200"]
    elasticsearch.username: "elastic"
    elasticsearch.password: "senha-segreda"
    monitoring.ui.container.elasticsearch.enabled: true
    logging.verbose: true
    xpack.security.enabled: true
    xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters"
    xpack.reporting.encryptionKey: "something_at_least_32_characters"
    xpack.security.sessionTimeout: 600000
    xpack.reporting.capture.browser.chromium.disableSandbox: true
    telemetry.optIn: false
    telemetry.enabled: false