apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
    component: messaging
data:
  server.properties: |
    # Kafka Configuration
    broker.id=${BROKER_ID}
    num.network.threads=3
    num.io.threads=8
    socket.send.buffer.bytes=102400
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    log.dirs=/var/lib/kafka/data
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    log.retention.hours=168
    log.segment.bytes=1073741824
    log.retention.check.interval.ms=300000
    zookeeper.connect=zookeeper:2181
    zookeeper.connection.timeout.ms=18000
    group.initial.rebalance.delay.ms=0
    listeners=PLAINTEXT://:9092
    advertised.listeners=PLAINTEXT://${POD_NAME}.kafka:9092
    auto.create.topics.enable=true
    delete.topic.enable=true
    compression.type=producer
    message.max.bytes=1000012
    replica.fetch.max.bytes=1000012
    max.request.size=1000012
    fetch.max.bytes=1000012