apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: zookeeper
    component: messaging
data:
  zoo.cfg: |
    tickTime=2000
    dataDir=/data
    clientPort=2181
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=true
    admin.enableServer=true