# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana
#   labels:
#     app.kubernetes.io/name: grafana
# spec:
#   selector:
#     app.kubernetes.io/name: grafana
#   ports:
#   - name: http
#     port: 3000
#     targetPort: 3000
#     nodePort: 3000
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  type: ClusterIP
  selector:
    app: grafana
    app.kubernetes.io/component: visualization
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
  ports:
    - name: http
      port: 3000
      targetPort: 3000
