all:
  children:
    debian:
      hosts:
        172.23.161.197:
          ansible_user: fabiossena
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_pass: "{{ become_pass }}"
