all:
  children:
    debian:
      hosts:
        # 172.23.161.197:
        localhost:
          ansible_connection: local
          ansible_user: fabiossena
          ansible_become: true
          ansible_become_method: sudo
          ansible_python_interpreter: /usr/bin/python3.13
          # ansible_python_interpreter pode ser adicionado se Python estiver em caminho não padrão
          
