all:
  children:
    debian:
      hosts:
        172.23.161.197:
          ansible_user: root
          ansible_become: true
          ansible_become_method: sudo
          # ansible_python_interpreter pode ser adicionado se Python estiver em caminho não padrão
          
