apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickvisual
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: clickvisual
  template:
    metadata:
      labels:
        app: clickvisual
    spec:

      initContainers:
        - name: init-db
          image: mysql:8.0
          command:
            - sh
            - -c
            - |
              until mysql -h {{ .Values.mysql.host }} -u {{ .Values.mysql.user }} -p{{ .Values.mysql.password }} -e "SELECT 1"; do
                sleep 3
              done
              mysql -h {{ .Values.mysql.host }} -u {{ .Values.mysql.user }} -p{{ .Values.mysql.password }} {{ .Values.mysql.database }} < /init/database.sql
          volumeMounts:
            - name: db-init
              mountPath: /init

      containers:
        - name: clickvisual
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - /clickvisual/bin/clickvisual

          args:
            - server
            - -config
            - /clickvisual/config/default.toml

          env:
            - name: TZ
              value: {{ .Values.timezone }}

          ports:
            - containerPort: 3001

          volumeMounts:
            - name: config
              mountPath: /clickvisual/config
            - name: data
              mountPath: /clickvisual/data

          resources:
            {{ toYaml .Values.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 120

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3001
            initialDelaySeconds: 120

      volumes:
        - name: config
          configMap:
            name: clickvisual-config

        - name: db-init
          configMap:
            name: clickvisual-db-init

        - name: data
          persistentVolumeClaim:
            claimName: clickvisual-pvc
