apiVersion: v1
kind: Service
metadata:
  name: clickvisual
spec:
  type: {{ .Values.service.type }}
  selector:
    app: clickvisual
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
