apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- service-client.yaml
- configmap.yaml
- secret.yaml

commonLabels:
  app: elasticsearch
  component: search
  managed-by: kustomize
  part-of: platform

secretGenerator:
- name: elasticsearch-secret
  literals:
  - password=senha-segreda