apiVersion: v1
kind: Service
metadata:
  name: grafana
  # namespace: observability
spec:
  type: ClusterIP
  ports:
    - port: 3000
      nodePort: 32000   # porta externa
  selector:
    app: grafana
