apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app: rabbitmq
    component: messaging
data:
  rabbitmq.conf: |
    ## Networking
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    management.tcp.ip   = 0.0.0.0
    
    ## Clustering
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    
    ## Memory
    vm_memory_high_watermark.absolute = 2GB
    vm_memory_high_watermark_paging_ratio = 0.5
    
    ## Disk
    disk_free_limit.absolute = 2GB
    
    ## Default user/pass
    default_user = admin
    default_pass = senha-segreda
    
    ## Enable plugins
    management.load_definitions = /etc/rabbitmq/definitions.json