apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- service-client.yaml
- configmap.yaml
- secret.yaml

commonLabels:
  app: rabbitmq
  component: messaging
  managed-by: kustomize
  part-of: platform

secretGenerator:
- name: rabbitmq-secret
  literals:
  - erlang-cookie=SWQKDFJSLKDFJSLKDFJ
  - username=admin
  - password=senha-segreda