apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-namespace
resources:
- namespace.yaml
- ../../base
patches:
- path: main-patch.yaml
commonLabels:
  env: staging


images:
- name: ghcr.io/fabiossena/anchor-api
  newName: ghcr.io/fabiossena/anchor-api
  newTag: b6d0fddbc07b0eb28fd6b7b5c5a0e8068c9b9426
- name: ghcr.io/fabiossena/redpanda-producer-api
  newName: ghcr.io/fabiossena/redpanda-producer-api
  newTag: dbee9b7915de0f40e0408362509c0e1a620551ba
