apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anchor-api
  template:
    metadata:
      labels:
        app: anchor-api
    spec:
      # initContainers:
      # - name: init-sqlite
      #   image: busybox
      #   command:
      #     - sh
      #     - -c
      #     - |
      #       mkdir -p /var/www/html/database && \
      #       touch /var/www/html/database/database.sqlite
      #   volumeMounts:
      #     - name: database-storage
      #       mountPath: /var/www/html/database

      containers:
      - name: anchor-api
        image: ghcr.io/fabiossena/anchor-api:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80

        envFrom:
          - configMapRef:
              name: anchor-api-config
          - secretRef:
              name: anchor-api-secrets
        volumeMounts:
          - name: database-storage
            mountPath: /var/www/html/database

      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: anchor-api-pvc
