- hosts: all
  become: yes
  roles:
    - base

- hosts: debian
  roles:
    - role: k3s
      tags: k3s
    - role: argocd
      tags: argocd
    - role: k9s
      tags: k9s

#- import_playbook: ansible/playbooks/bootstrap.yml