apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickvisual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickvisual
  template:
    metadata:
      labels:
        app: clickvisual
    spec:
      containers:
        - name: clickvisual
          image: clickvisual/clickvisual:latest
          ports:
            - containerPort: 3000

          volumeMounts:
            - name: config
              mountPath: /clickvisual/config/default.toml
              subPath: default.toml

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: config
          configMap:
            name: clickvisual-config
