apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickvisual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickvisual
  template:
    metadata:
      labels:
        app: clickvisual
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: clickvisual
          image: clickvisual/clickvisual:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          envFrom:
            - secretRef:
                name: clickvisual-secret

          volumeMounts:
            - name: config
              mountPath: /clickvisual/config/default.toml
              subPath: default.toml

      volumes:
        - name: config
          configMap:
            name: clickvisual-config
