apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickvisual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickvisual
  template:
    metadata:
      labels:
        app: clickvisual
    spec:
      containers:
        - name: clickvisual
          image: ghcr.io/clickvisual/clickvisual:v1.1.5
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: clickvisual-config
            - secretRef:
                name: clickvisual-secret
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10