apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - templates/deployment.yaml
  - templates/service.yaml
  - templates/pvc.yaml
  - templates/configmap.yaml
  - templates/configmap-db.yaml