apiVersion: v1
kind: Service
metadata:
  name: clickvisual
  namespace: production-observability
spec:
  selector:
    app: clickvisual
  ports:
    - port: 80
      targetPort: 3001
      name: http
  type: ClusterIP