apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - statefulset.yaml
  - service.yaml
  - pvc.yaml
  - promtail/config.yaml
  - promtail/daemonset.yaml
  - promtail/rbac.yaml

# commonLabels:
#   app.kubernetes.io/part-of: loki-stack
#   app.kubernetes.io/managed-by: argocd